import Head from "next/head";
import { Typography } from "@mui/material";
import Layout from "../compoents/Layout";

export default function Home() {
	return (
		<Layout title="E-Commerce website Amazona" description="A modern ecommerce site">
			List Products working
		</Layout>
	);
}

// <div>
// 			<Head>
// 				<title>E-commerce website</title>
// 				<meta name="description" content="Generated by create next app" />
// 				<link rel="icon" href="/favicon.ico" />
// 			</Head>

// 			<Typography component="h1" variant="h1">
// 				Sanity Amazona
// 			</Typography>
// 		</div>
